### ISSUE TITLE
Cannot open setting panel in Arc browser

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#10]
Arc browser: https://arc.net/

**Comment by sapjax** [comment]
It's using the [sidePanel](https://developer.chrome.com/docs/extensions/reference/sidePanel/) API, introduced in Chrome 114+, the Arc may not be up to date with Chrome.

But I checked it in the code, and if not supported, should open the settings page instead settings side panel.

I guess the problem is Arc has `sidePanel` API, but has not implemented it fully yet.

right now, you can right-click on the extension icon and press **options** link to settings.

**Comment by pasiooooo** [comment]
> right now, you can right-click on the extension icon and press **options** link to settings. 

Thanks for your brilliant work! It works.

It is expected that this problem can be completely solved in the future.

**Comment by sapjax** [comment]
It seems Arc has no plan to fix this issue, just close now.
