### ISSUE TITLE
Unable to monitor newly generated sentences via AJAX

### ISSUE THREAD

**Issue by CEX68** [sapjax/word-hunter#35]
Word Hunter is unable to monitor newly generated sentences via AJAX, such as on https://chat.openai.com/. A manual refresh is required for it to function.

**Comment by sapjax** [comment]
@CEX68 
This is because the chatGPT page changes the result text steam via `nodeValue` after appending the text node, and we didn't observe the text node content change. 

This has been fixed in https://github.com/sapjax/word-hunter/commit/4ef8b61b138631c19986acd5d28a2d3f0e41bf40 , will be released in v1.1.6

**Comment by CEX68** [comment]
Doesn't pop up dict on some words on https://adarkroom.doublespeakgames.com/ with version 1.1.7
<img width="702" alt="1" src="https://github.com/sapjax/word-hunter/assets/115330187/9e24b4e8-1f5e-4dd4-b4cf-91f8a7a49b9b">

**Comment by sapjax** [comment]
> Doesn't pop up dict on some words on https://adarkroom.doublespeakgames.com/ with version 1.1.7 

The web pages block mouse events and have nothing to do with chrome extensions.
