### ISSUE TITLE
这个插件会导致页面未响应，原因不太明白。机器配置很高，以前从来没出现这种情况

### ISSUE THREAD

**Issue by majiayu000** [sapjax/word-hunter#36]
这个插件会导致页面未响应，原因不太明白。机器配置很高，以前从来没出现这种情况

**Comment by sapjax** [comment]
@majiayu000 
try to disable the `show Chinese translation` on the options page.
if there are too many translations, the performance is terrible.

**Comment by sapjax** [comment]
I can confirm this is a bug when both conditions matched:
- dynamic change the `show Chinese translation` setting.
- have the unknown words `a` or `an` on page.

This is a strange bug, I will figure it out later.

**Comment by sapjax** [comment]
This problem is caused by:
1. the `a` or `an` has the translation `art. (意义参见 a条。)`
2. when inserting the translation into the page, the inserted node observed by extension
3. then `art` word in translation is highlighted and translated too.
4. then a translation node for `art` is inserted into page.
5. which breaks the translation node of `a` or `an`, the extension observes the node changed, and tries to highlight and translate the translation node again.
6. then jump to step 2 again, and enter an endless loop, so the page has no response.

This bug will be fixed and released in v1.1.7.

**Comment by majiayu000** [comment]
Thanks for the fix！！
